"""
Settings for the local instance of our django app. 
WARNING: this file should
not be committed or shared with others.
"""
# To set your local settings, edit the values below and change the name of this
# file to 'local_settings.py'

# A secret key can be generated by opening a django shell and running the
# get_secret_key() function. Copy and past it in below.
# python manage.py shell
# from django.core.management.utils import get_random_secret_key
# get_random_secret_key()
SECRET_KEY = '#*4^he=p495+3dj34qit+lsb61$yfgcbrg9-(sle04al!yv*r+'

# Debug should be set to False for production environments, True for dev
# environments.
DEBUG = True

# This can be blank if debug is True else it should contain the names of the
# appropriate servers.
ALLOWED_HOSTS = []


# The bellow settings can be used to ensure that cookie data is only sent over
# secure HTTPS connections. Set them to True if this is the case. Note that this
# requires you to have HTTPS active on your site.
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

# # Setting up you database. Bellow are settings for a MySQL batabase. If you
# # leave these commented out your site will use a sqlite database.
'''
DATABASES = {
     'default': {   
         'ENGINE': 'django.db.backends.mysql',
         'NAME': '[DATA BASE NAME]',
         'USER': '[USER NAME]',
         'PASSWORD': '[USER PASSWORD]',
         'HOST': '[HOST]',
     }
 }
'''

# EMAIL SETTINGS

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'akshayvollala779@gmail.com'
EMAIL_HOST_PASSWORD = 'wrywdwtfanlsppbc'

# Settings for a demo user that people can use without registering for their own
# account.  
# IMPORTANT :
# This user should be set up using an admin account and MUST have the
# profile.is_demo_user set to true.
DEMO_USER_USERNAME = "guestuser"
DEMO_USER_PASSWORD = "guestuserpassword"
